[project]
name = "blackmagic-transport"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "certifi>=2025.8.3",
    "pyinstaller>=6.16.0",
    "requests>=2.32.5",
]
